In [2]:
import pandas as pd

In [ ]:
# !pip install kagglehub     # to download dataset it is needed to run this command

  Using cached kagglehub-0.2.9-py3-none-any.whl.metadata (21 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
  Using cached charset_normalizer-3.4.1-cp38-cp38-win_amd64.whl.metadata (36 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Using cached kagglehub-0.2.9-py3-none-any.whl (39 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp38-cp38-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)


In [ ]:
# import kagglehub

# Download latest version
# path = kagglehub.dataset_download("zeeshier/t20-cricket-match-score-dataset")

# print("Path to dataset files:", path)

100%|██████████| 16.9k/16.9k [00:00<?, ?B/s]

Extracting model files...
Path to dataset files: C:\Users\khann\.cache\kagglehub\datasets\zeeshier\t20-cricket-match-score-dataset\versions\1


In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('data/t20_cricket_match_score_prediction.csv')

In [5]:
df.head()

Match ID  Overs Played  Wickets Lost  Run Rate Home/Away  \
0         1             7             1     11.04      Away   
1         2            20            10     11.87      Home   
2         3            15             7      6.14      Home   
3         4            11             8      8.84      Home   
4         5             8             0      9.56      Home   

   Opponent Strength Pitch Condition Weather  Predicted Score  
0                  3         Bowling   Sunny               82  
1                  5         Bowling   Sunny              204  
2                  7        Balanced   Sunny              105  
3                  9         Batting  Cloudy              121  
4                  2        Balanced   Sunny              104

In [6]:
df.columns=df.columns.str.replace(" ","_")

In [7]:
df.columns

Index(['Match_ID', 'Overs_Played', 'Wickets_Lost', 'Run_Rate', 'Home/Away',
       'Opponent_Strength', 'Pitch_Condition', 'Weather', 'Predicted_Score'],
      dtype='object')

In [8]:
df.to_csv('t20_cricket_match_score_prediction_final.csv',index=False)

In [9]:
df.shape

(1500, 9)

In [10]:
df['Overs_Played'].unique()

array([ 7, 20, 15, 11,  8, 19,  4,  3,  2, 12,  6,  1, 17, 10, 16,  5,  9,
       18, 14, 13], dtype=int64)

In [11]:
df['Wickets_Lost'].unique()

array([ 1, 10,  7,  8,  0,  4,  3,  6,  2,  9,  5], dtype=int64)

In [12]:
df['Run_Rate'].unique()

array([11.04, 11.87,  6.14,  8.84,  9.56,  8.69,  6.21,  9.19, 12.51,
        5.71,  5.8 ,  8.55, 14.42, 11.69, 11.79,  8.62, 10.94,  5.1 ,
       11.36, 14.13, 11.13, 13.74, 12.24, 14.02,  5.66, 10.34,  6.42,
        5.12,  9.22,  7.95,  9.86, 10.77,  5.44,  6.23, 10.59,  8.43,
       12.29, 11.52, 13.46, 11.92,  9.3 , 11.73,  7.75,  8.06, 12.89,
        9.46, 12.98, 13.22, 13.58, 14.17,  9.31,  8.19, 10.82,  8.71,
       11.01, 12.06, 11.88,  8.75,  6.67,  6.43, 13.9 ,  8.46,  6.54,
        5.25, 11.46, 11.37,  8.41,  5.72,  9.1 ,  8.11, 11.77, 11.06,
        8.65,  7.18, 14.88,  9.54,  6.41,  5.28, 10.05, 14.64,  5.39,
        5.31,  8.88,  6.6 ,  5.23, 12.56,  9.59,  7.89, 14.  ,  6.16,
       14.56,  8.14, 13.88, 11.03, 13.27, 14.84,  7.88, 14.61,  8.89,
        8.86,  8.4 , 10.41, 10.54, 10.42, 12.62, 13.34,  9.4 ,  8.02,
        7.59,  6.95,  5.58,  8.42,  7.7 , 14.66, 10.58,  8.47, 10.8 ,
        6.39,  9.44, 11.26,  9.89,  9.02, 14.94, 13.8 , 11.23, 10.69,
       11.21,  7.01,

In [13]:
df['Home/Away'].unique()

array(['Away', 'Home'], dtype=object)

In [14]:
df['Opponent_Strength'].unique()

array([ 3,  5,  7,  9,  2,  4,  1, 10,  6,  8], dtype=int64)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Match_ID           1500 non-null   int64  
 1   Overs_Played       1500 non-null   int64  
 2   Wickets_Lost       1500 non-null   int64  
 3   Run_Rate           1500 non-null   float64
 4   Home/Away          1500 non-null   object 
 5   Opponent_Strength  1500 non-null   int64  
 6   Pitch_Condition    1500 non-null   object 
 7   Weather            1500 non-null   object 
 8   Predicted_Score    1500 non-null   int64  
dtypes: float64(1), int64(5), object(3)
memory usage: 105.6+ KB


In [16]:
df['Pitch_Condition'].unique()

array(['Bowling', 'Balanced', 'Batting'], dtype=object)

In [17]:
df['Weather'].unique()

array(['Sunny', 'Cloudy', 'Overcast'], dtype=object)

In [18]:
df['Predicted_Score'].unique()

array([ 82, 204, 105, 121, 104,  55, 125,  92, 159,  31,  44,  37,  48,
       133,  80,  43,  18,  85, 158, 218, 115, 212, 209, 132, 232,  65,
       172,  34,  45, 207,  73,  69, 106, 130,  42, 131, 182, 340, 234,
        72,  38, 279,  70, 301, 108,  39,  36,  93,  91,  61, 190, 150,
        35,  60, 201, 164,  54,  74, 193,  88, 140, 188,  83, 138, 179,
       134,  66,  76, 281,  67,  21,  20,  32,  58, 128, 151, 152,  23,
        28,  64,  46,  52, 107, 169,  50,  15, 102, 114,  96, 119,  81,
        75, 141, 112, 194,  71, 167, 117, 222, 174,  77, 168,  27, 101,
        79, 356,  29, 110, 220,  24, 248,  78, 186, 149, 233, 236, 254,
       250,  25,  22,  14, 285, 176,  56,  98, 211,  49, 272,  59,  86,
        87, 181, 278, 309, 227,  84, 288,  57, 241,  53,  33, 185,  12,
       200, 165,  51,  97, 192,  16, 217, 214, 142, 267, 144,  41, 229,
       197, 154, 100,  90,  26, 126, 202, 178, 170, 146,  68,  30, 252,
        62, 175, 230, 171, 137,  19, 111, 205, 173, 161, 180, 15

In [19]:
df['Predicted_Score'].max()

382

In [20]:
df.isnull().sum()

Match_ID             0
Overs_Played         0
Wickets_Lost         0
Run_Rate             0
Home/Away            0
Opponent_Strength    0
Pitch_Condition      0
Weather              0
Predicted_Score      0
dtype: int64

In [21]:
numeric_features= [feature for feature in df.columns if df[feature].dtype != "object"]
categorical_features= [feature for feature in df.columns if df[feature].dtype == "object"]

print('we have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nwe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

we have 6 numerical features : ['Match_ID', 'Overs_Played', 'Wickets_Lost', 'Run_Rate', 'Opponent_Strength', 'Predicted_Score']

we have 3 categorical features : ['Home/Away', 'Pitch_Condition', 'Weather']


In [22]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [23]:
X = df.drop(columns=['Predicted_Score'],axis=1)

In [24]:
y=df['Predicted_Score']

In [25]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [26]:
X = preprocessor.fit_transform(X)

In [27]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((1200, 13), (300, 13))

In [28]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [29]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 21.0507
- Mean Absolute Error: 15.2960
- R2 Score: 0.9145
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 21.2130
- Mean Absolute Error: 16.0133
- R2 Score: 0.9117


Lasso
Model performance for Training set
- Root Mean Squared Error: 21.4048
- Mean Absolute Error: 15.4553
- R2 Score: 0.9116
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 21.1769
- Mean Absolute Error: 16.0393
- R2 Score: 0.9120


Ridge
Model performance for Training set
- Root Mean Squared Error: 21.0087
- Mean Absolute Error: 15.2606
- R2 Score: 0.9148
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 21.0081
- Mean Absolute Error: 15.8872
- R2 Score: 0.9134


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 18.5415
- Mean Absolute Error: 14.3748
- R2 Score: 0.9336
---------

In [30]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

Model Name  R2_Score
7    CatBoosting Regressor  0.999319
6             XGBRegressor  0.989424
5  Random Forest Regressor  0.982769
4            Decision Tree  0.955587
2                    Ridge  0.913375
1                    Lasso  0.911977
0        Linear Regression  0.911676
8       AdaBoost Regressor  0.909464
3    K-Neighbors Regressor  0.900052